services:
  - type: cron
    name: workcenter-log-cronjob
    env: docker
    schedule: "*/10 * * * *"  # Ejecutar cada 10 minutos
    dockerfilePath: ./Dockerfile
    repo: https://github.com/miguelsot0b/workcenter-log
    branch: main
    envVars:
      - key: PLEX_USERNAME
        sync: false
      - key: PLEX_PASSWORD
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_BASE64
        sync: false
      - key: GOOGLE_DRIVE_FILE_ID
        sync: false
